<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\BuildingBlocks.Application\BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\BuildingBlocks.Domain\BuildingBlocks.Domain.csproj" />
    <ProjectReference Include="..\..\Modules\Adhkar\Adhkar.Domain\Adhkar.Domain.csproj" />
    <ProjectReference Include="..\..\Modules\Adhkar\Adhkar.Application\Adhkar.Application.csproj" />
    <ProjectReference Include="..\..\Modules\Recitations\Recitations.Domain\Recitations.Domain.csproj" />
    <ProjectReference Include="..\..\Modules\Recitations\Recitations.Application\Recitations.Application.csproj" />
    <ProjectReference Include="..\..\Modules\Tasbeeh\Tasbeeh.Domain\Tasbeeh.Domain.csproj" />
    <ProjectReference Include="..\..\Modules\Tasbeeh\Tasbeeh.Application\Tasbeeh.Application.csproj" />
    <ProjectReference Include="..\..\Modules\Questions\Questions.Domain\Questions.Domain.csproj" />
    <ProjectReference Include="..\..\Modules\Questions\Questions.Application\Questions.Application.csproj" />
    <ProjectReference Include="..\..\Modules\Content\Content.Domain\Content.Domain.csproj" />
    <ProjectReference Include="..\..\Modules\Content\Content.Application\Content.Application.csproj" />
    <ProjectReference Include="..\..\Modules\Kids\Kids.Domain\Kids.Domain.csproj" />
    <ProjectReference Include="..\..\Modules\Kids\Kids.Application\Kids.Application.csproj" />
    <ProjectReference Include="..\..\Modules\Notifications\Notifications.Domain\Notifications.Domain.csproj" />
    <ProjectReference Include="..\..\Modules\Notifications\Notifications.Application\Notifications.Application.csproj" />
    <ProjectReference Include="..\..\Modules\Administration\Administration.Domain\Administration.Domain.csproj" />
    <ProjectReference Include="..\..\Modules\Administration\Administration.Application\Administration.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Persistence\SeedData\*.json" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
